### ISSUE TITLE
Bug new composition's name

### ISSUE THREAD

**Issue by Check-mate** [GridSound/daw#11]
Hi

When I try to save a new composition (by pressing CTRL-S or directly by clicking the button), unfortunately, not all characters are taken into consideration.
If I want to write: "**azertyuiopqsdfghjklmwxcvbn**", only "aertyuiopqfjklmwxn" is process.
Missing letter: **z**, **s**, **d**, **g**, **h**, **c**, **v**, **b**

I tested on Windows 10, Firefox 50.1.0.

**Comment by Mr21** [comment]
Oh... true :(

I just recode the `window.prompt` object and I have now some conflict with the keyboard shortcut part...
Each missing letter is a part of at least one keyboard shortcut.

Thanks a lot :)

**Comment by Mr21** [comment]
Fixed with https://github.com/GridSound/gs-ui-components/commit/2c79d36bc33b676e56169cf11bded9a18616a5f4#diff-c0ea747e7f0ffb26ac2f9b3f360126f7
:)
