### ISSUE TITLE
Playback continues while playhead stops/disappears 

### ISSUE THREAD

**Issue by JasonMillward** [gridsound/daw#12]
This ones a bit hard to explain, so I've included a video: https://www.youtube.com/watch?v=EbmQCNS8vt4

For certain sound files the playhead stops as if its reached the end of the workspace, but the audio is still played. 

Sound files used: [soundfiles.zip](https://github.com/GridSound/daw/files/725711/soundfiles.zip)

**Comment by Mr21** [comment]
Hi :)

Your video is not available, but I know there is still one big bug on our webaudio library.
The composition's duration is calculated with the last sorted sample. But sometimes another sample before the last one can be longer. And the sound will continue, but all the UI is stopped...

**Comment by Mr21** [comment]
Do you want me to invite you to join our slack channel? (gridsound.slack.com)
By the way, the whole DAW is being cuted in 3 others separated repositories (see this [map links](https://github.com/GridSound/daw/wiki)), after that rewrite part done, the code will be a lot more simple.

**Comment by JasonMillward** [comment]
So sorry, I left the video as private, it has been fixed now but you seem to know the issue I'm referring to. 

I'll gladly take an invite to the slack channel and lend a hand where I can.

**Comment by Mr21** [comment]
So yes, don't worry this bug is already fixed, but the "daw" repo doesn't this code for the moment...
Can I have your email (or if you prefer you can send it to me at thomastortorini@gmail.com)
