### ISSUE TITLE
Switch from Make to a Native JS build tool

### ISSUE THREAD

**Issue by derekmwright** [gridsound/daw#13]
I'd like to propose a switch from the make script to a native JS build tool in order to be platform independent. Before I begin any work on it, I wanted to get your thoughts on it and see if there is a build tool you guys would lean towards?

**Comment by Mr21** [comment]
Hi :) thanks a lot to you to want contribute with us!
Currently (since 3 months) the whole project is being separated into 4 differents GH repos. I would prefer to wait before changing the build :/ (more info at https://github.com/GridSound/daw/wiki).
Do you want me to invite you on our slack?

**Comment by derekmwright** [comment]
Sure, I'd like to be able to help out.
