### ISSUE TITLE
Last version is broken (Uncaught TypeError: Cannot read property 'content' of null)

### ISSUE THREAD

**Issue by Agnostic** [gridsound/daw#15]
I have downloaded the last source, after installing all dependencies and running the app, I got this error:

![screen shot 2017-06-02 at 12 01 09 pm](https://cloud.githubusercontent.com/assets/1162988/26736326/36c81332-478b-11e7-8a0d-b66408c9d850.png)

`e.appendChild(document.importNode(gsuiToggle.template.content,!0)),e.r`

**Comment by Mr21** [comment]
Hi @Agnostic, sorry for the delay..

Actually the online version use two constante statics files: `gs-daw.min.js` and `gs-daw.min.css`, these two files can't be recompiled, the original source code is gone.

The entire project is being rewrite in a component way.
The UI/Audio components can be seen on [CodePen](https://codepen.io/mr21/).
After the UI components are stored at [gs-ui-components](https://github.com/GridSound/gs-ui-components) and the Audio components at [gs-webaudio-library](https://github.com/GridSound/gs-webaudio-library).

If you want to contribute I will be happy to invite you to our Slack :)
