### ISSUE TITLE
Is this fully functional?

### ISSUE THREAD

**Issue by tonikami** [gridsound/daw#16]
Hi, we followed all the steps in your "How to build" guide, however, the blocks can be added but they can't be moved around, the play button isn't working etc. 

Just wondering if it is still working, or if the changes to the components have broken it. 

Great work btw! Would like to join your slack too 👍

**Comment by Mr21** [comment]
Hi :)

Yeah you have fully understand the problem, but I am rushing the end of a new version.
But fortunately it is not necessary to build the project to be able to code some new vanilla components.
Anyway, thanks a lot for your understanding and your interest :) I need your email for the Slack (send me an email if you want).

**Comment by tonikami** [comment]
Thanks for the response, I've sent you an email :)
