### ISSUE TITLE
Mixer

### ISSUE THREAD

**Issue by mistaox** [gridsound/daw#17]
Awesome project!

Are there any plans to add a mixer like: 
http://kevvv.in/mix/
https://github.com/kevincennis/Mix.js

**Comment by Mr21** [comment]
Hi :)

Yes, a mixer will be added in the future version (https://gridsound.github.io/daw/_new.html).
The main next feature in coming is the *Piano Roll*.

**Comment by mistaox** [comment]
That looks amazing!

**Comment by mr21** [comment]
![image](https://user-images.githubusercontent.com/850754/67730437-5501dd00-f9f5-11e9-8544-fdec367746e0.png)

The Mixer and a separate Fx window are ready :)
