### ISSUE TITLE
Feature Request: Save and Load Composition from Server-side or URL

### ISSUE THREAD

**Issue by mistaox** [gridsound/daw#18]
Is there a mechanism to allow  loading a composition  from a URL or local resource on the server instead of dragging to the browser?

Thanks

**Comment by Mr21** [comment]
Currently no. But it's in the plan to have a backend to show/save/restore any compositions, with all the collaborative features like follow someone, star a composition, etc.

But if you want to have your own server, we will have to set a feature to let the user able to load a composition from another distant server.

But yes it's definitely in the plan :)

**Comment by mistaox** [comment]
Awesome.  I'm building( actualy paying a dev team)  a music related platform. A browser based DAW like this is a feature I hope to add at some point.

**Comment by Mr21** [comment]
Thanks for your interesting :)
I will launch a Kickstarter soon to be able to continue the work on that.
Maybe you will want to be notified?

**Comment by mistaox** [comment]
Yes. That is a good idea.
