### ISSUE TITLE
Select a pattern

### ISSUE THREAD

**Issue by DerouckClovis** [gridsound/daw#20]
Hi guys,

To select a pattern actually we have to **double click it** either in the left side or in the top side.
I suggest we could **click once** on the top border of the pattern (red on the screenshot) and keep it like that for the green part.

![sans titre](https://user-images.githubusercontent.com/18465625/32719895-2b92e9da-c862-11e7-9065-f0e9d0218ad6.png)

It would be more intuitive for sure, I had some troubles changing patterns as it is actually.

Keep up the great work !

**Comment by Mr21** [comment]
This section needs clearly a brainstorming... in this [reddit thread](https://www.reddit.com/r/coolgithubprojects/comments/78qx2b/gridsound_a_workinprogress_digital_audio/dowzl6m/), somebody gives another interesting feedback on this same area.

I don't know exactly what is the best solution, but I will try something with buttons appearing at :hover.

**Comment by mr21** [comment]
In the future release, the patterns' behaviour on the left list has changed. To be sure to be more intuitive **all** the pattern's area will select the pattern once clicked.
There is (for the moment) no more preview, we will see where to add a button latter.
