### ISSUE TITLE
History Ergonomy and ShortCuts

### ISSUE THREAD

**Issue by DerouckClovis** [gridsound/daw#21]
Hey,

I was trying to use shortcuts on Windows, but it didn't work.
So far, the only manipulations that worked for me was : 
- Shift + Click - Select elements
- Alt + Click - Drag patterns vertically and horizontally 
- Ctrl + Scroll In/Out - Zoom In/Out

**Ctrl+Z, Ctrl+Shift+Z, Ctrl+C, Ctrl+V,** etc... those didn't work.

So I looked for a way to undo what I did and I found it in history.
I suggest you open history as **height 90** by default.
As you can see in the below screenshot, that could let the user know there is those button **Undo Redo**, as well as seeing at least **the last thing** he did in the **GridSound**.

![sans titre](https://user-images.githubusercontent.com/18465625/32720244-37951644-c863-11e7-8a00-d64ddfc029a0.png)

Keep up the great work !

**Comment by Mr21** [comment]
Hi :)

Thanks for the idea and your interest. For the moment we do not have the `Ctrl+C/V` because it's pretty difficult to find a smart logic to where add the `Ctrl+V` result... So I am planning to add a `Alt+Click` to duplicate the selection where you want. Exactly like Photoshop for example.

Why the `Ctrl+[Shift+]Z` is not working is a serious issue... Are you on Chrome Windows 10 ?

**Comment by Mr21** [comment]
Also, good idea for the `90px`, I am rewriting the [`gsuiPanels`](https://github.com/gridsound/gs-ui-components/tree/master/gsuiPanels) component anyway... thanks a lot for your feedbacks.

**Comment by DerouckClovis** [comment]
I run GridSound on Chrome, Windows 10, yes.

I understand the point with Ctrl+V, it could be a great idea to Alt+Click the selection 👍 
But if you do that, remember to keep the Alt+Click that allow us to move in the lower right screen. Ahah

Anyway, good luck with your project, I'll be around trying things out from time to time, if that can help.

**Comment by Mr21** [comment]
Yes well seen :), the alt+click to duplicate will be trigger only if you click a (selected or not) block.
Thanks for your encouragement :)

**Comment by Timer91** [comment]
This issue is due to `window.onkeydown` which use `e.code` instead of `e.keyCode`. It is fixed in #27 PR.
