### ISSUE TITLE
Idées générales à rajouter dans la todolist

### ISSUE THREAD

**Issue by Mr21** [gridsound/daw#3]
##### Outils
- Avoir un métronome, essentiel pour s'enregistrer en étant dans la mesure.
- Gérer le protocole [**MIDI**](https://fr.wikipedia.org/wiki/Musical_Instrument_Digital_Interface) en entrée (pouvoir recevoir des informations depuis un clavier usb/midi) et en sortie (pouvoir envoyer des informations midi à son appareil usb/midi).
- Avoir au moins un plugin de génération de sons synthétiques (sur la base d'un ajout de signaux sortis d'oscillateurs).
- Avoir au moins les plugins suivant : [**EQ**](https://fr.wikipedia.org/wiki/%C3%89galiseur), [**Compresseur**](https://fr.wikipedia.org/wiki/Compresseur_%28audio%29), [**Reverb**](https://fr.wikipedia.org/wiki/R%C3%A9verb%C3%A9ration_%28acoustique%29), [**Délai**](https://fr.wikipedia.org/wiki/Delay_%28effet%29).
##### Améliorations UI
- [~~Afficher les mesures en plus du temps (avec un affichage `h:m:s.ms - Mesure`)~~](https://github.com/GridSound/gridsound.github.io/commit/4984b964c3112efccd337f8731d446b5613a87fa)
- Permettre la gestion du _panoramique_ (mettre un son plus à droite ou plus à gauche)
- Permettre de baisser ou monter le son d'un clip (mettre un son plus fort ou moins fort).
- Permettre de modifier la [**signature rythmique**](https://fr.wikipedia.org/wiki/Mesure_%28notation_musicale%29#Types) de tout le morceau, actuellement le `4/4` est obligatoire alors qu'il y a beaucoup de morceaux en `3/4`.
- Permettre de modifier la signature rythmique dans le morceau (démarrer 16 mesures en `4/4` puis avoir un break de 1 mesure en `2/4`).
- Ajouter un didacticiel ou page d'aide sur les différentes fonctionnalités.
- Permettre d'avoir ses propres raccourcis pour réaliser les actions.
- Gérer des groupes de pistes (pouvoir regrouper différentes prises de voix).
- Mettre une icône et une couleur sur chaque piste pour les différencier.
- Décider du nombre de pistes présentes dans le morceau, actuellement il y en a 43, est-ce vraiment utile? Le mieux serait de pouvoir choisir.  
  En général dans un petit morceau (rock ou électro) il y a 14 pistes minimum:
  - **Basse**.
  - **Instrument rythmique mélodique** (guitare rythmique et/ou piano).
  - **Instrument lead** (guitare solo, etc.).
  - **Voix lead** (chant principal).
  - **backing** (voix de fond).
  - **Batterie** (ou **rythme**) qui peut être éclatée en 9 sous-pistes:
    - 1 Grosse caisse
    - 1 Caisse claire
    - 1 Charlestone
    - 2 Cymbales Crash
    - 1 Cymbale Ride
    - 1 Tom Aigu
    - 1 Tom Médium
    - 1 Tom Grave
##### Enregistrement et export
- [~~Pouvoir sauvegarder et reprendre une composition.~~](https://github.com/GridSound/gridsound.github.io/commit/16e3d75b781ad222ca72ce736aae993e4fc5b86b)
- Permettre d'enregistrer de l'audio en temps réel via le micro du PC ou un interface audio.
- Pouvoir définir un nombre de mesure totale pour le composition.
- Pouvoir exporter la composition en [**WAV**](https://fr.wikipedia.org/wiki/WAVEform_audio_format) [**AIFF**](https://fr.wikipedia.org/wiki/Audio_Interchange_File_Format) [**MP3**](https://fr.wikipedia.org/wiki/MPEG-1/2_Audio_Layer_3) [**Ogg Vorbis**](https://fr.wikipedia.org/wiki/Vorbis).

---
- Gestion des utilisateurs
  - Gérer une bibliothèque de samples.
  - Avoir une liste des compositions enregistrées.
- Collaboration sur une même composition
  - Permettre de modifier à plusieurs en même temps la même composition (le logiciel [_OhmStudio_](https://www.ohmstudio.com) propose cette fonctionnalité).
# 

Merci à **Patrick-André MARENDAT** pour ce retour :+1:

**Comment by admin96** [comment]
I would say that you need two additional plugins, a subtractive synth and an FM synth. This would be a good start for laying out a synth plugin architecture. Additionally, you may need a piano roll, sequencer and a mixer!

**Comment by Mr21** [comment]
Hi @admin96, thanks you for your interest :)

Currently we are **thinking** on HOW to do all that. In GridSound, there is no equivalent to the *step sequencer* window of *FL Studio* for the moment.
I am working on looping a part of the composition, it's a small but needed feature and it's pretty hard to code it properly ^^
And just before, we were working on the undo/redo... a lot of works not on the "audio" part have to be done.
