### ISSUE TITLE
Notes created at wrong location

### ISSUE THREAD

**Issue by 1j01** [gridsound/daw#30]
![gridsound bug](https://user-images.githubusercontent.com/3630663/33620020-afdf2592-d9b4-11e7-9801-af7375003139.gif)

It's offset by half a cell when creating notes.
And also when resizing notes, but in that case it's reasonable.

So you could give [`_getMouseBeat`](https://github.com/gridsound/gs-ui-components/blob/f50f803a6188d5c90f89e9bef8124702697a3435/gsuiGridSamples/gsuiGridSamples.js#L193) a parameter, or split it into two functions,
one to give you the nearest position (with `round`), and you to give the cell (with `floor`),
maybe `_getBeatNearestToMouse` and `_getBeatForCellUnderMouse`

**Comment by Mr21** [comment]
Thanks, you right, I will investigate this to night

**Comment by Mr21** [comment]
Thanks again :)
