### ISSUE TITLE
Can't move within grids

### ISSUE THREAD

**Issue by phsyron** [gridsound/daw#32]
I can't help but notice that there doesn't seem to be a way to move in time. The keyboard shortcuts says it should be shift+scroll, but how do you scroll?

**Comment by Mr21** [comment]
If you use the wheel of your mouse without pressing any key, it will scroll vertically, normally (maybe you have found a bug) you just have to press `Shift` while scrolling exactly like before.

**Comment by phsyron** [comment]
ah. I see. I use a pen tablet, no scroll wheel. any other way?

**Comment by Mr21** [comment]
Arf... no i'm sorry we didn't even start to implemente tactill events :(
The priority is to have something usable with the mouse. But maybe a visible scrollbar could be great, I don't know.
