### ISSUE TITLE
Deleting a note unfocuses the notes area

### ISSUE THREAD

**Issue by 1j01** [gridsound/daw#33]
I was confused when Ctrl+A didn't work... turns out it was because I had deleted a note.

Note: starting dragging from the empty space then over notes works fine, but starting from a note doesn't.

**Comment by Mr21** [comment]
> Note: starting dragging from the empty space then over notes works fine, but starting from a note doesn't.

Yes, and is it something bad to you?

**Comment by 1j01** [comment]
I'm describing both good and bad in that sentence. I'm saying what works first in order to describe what doesn't work in terms of that, in order to highlight the inconsistency.

It's just this one case that doesn't work:

|                           	|                        	|                                                   	|
|---------------------------	|------------------------	|---------------------------------------------------	|
| Left click on background  	| ✅ focuses the area     	| (creates note)                                	|
| Left click on a note      	| ✅ focuses the area     	| (can then drag note)                              	|
| Right click on background 	| ✅ focuses the area     	| (can then delete notes by dragging) 	|
| Right click on note       	| ❌ *unfocuses* the area 	| (deletes note; can then delete more notes by dragging)               	|

**Comment by Mr21** [comment]
Ahhh yes you right, I didn't understand your last previous sentence.
I don't know why there are two different behaviours here.. I will investigate, thanks again :)
