### ISSUE TITLE
Is it possible to integrate discord into the daw to help new users in the future

### ISSUE THREAD

**Issue by mr21** [gridsound/daw#41]

**Comment by Picoseconds** [comment]
What kind of integration? RPC? A bot?

**Comment by mr21** [comment]
Hi @Picoseconds i was just thinking to add an iframe somewhere with discord on a specific channel inside it.
But finally it's not so important, i will probably just add a new button somewhere more visible

**Comment by Picoseconds** [comment]
That's possible with RPC
