### ISSUE TITLE
Make gridsound as a singing synthesis editer

### ISSUE THREAD

**Issue by YuzukiTsuru** [gridsound/daw#46]
I want to make gridsound as a singing synthesis editer GUI
but i can not format the index.html
Once I format it
It’s wrong
How can i fix it or have some idea for it
Many thanks

**Comment by 740291272** [comment]
Oh, I know it is build form build.sh

**Comment by 740291272** [comment]
do you have any example for using the piano roll

**Comment by mr21** [comment]
Hi :)
Sorry the codepen should be updated but it's not, i'm on it

**Comment by mr21** [comment]
The codepen is now fixed https://codepen.io/gridsound/pen/EERbNN :) thx again for noticed me it

**Comment by 740291272** [comment]
Thx for fix ^v^
