### ISSUE TITLE
Integrate with Tiki and enhance synth/effects

### ISSUE THREAD

**Issue by anonimo82** [gridsound/daw#48]
Dear, why don't you integrate synths from Wad (https://github.com/rserota/wad) and effects from Tuna (https://github.com/Theodeus/tuna)?
Then, what about integrating this with tiki (https://tiki.org/HomePage)?

**Comment by mr21** [comment]
Hi, firstly the entire project is mainly graphic and visual, i could say that 90% of the code is not related to audio. The majority is UI/UX design (CSS/HTML/databinding).

So yeah i could use Tuna or Wad or Tone.js etc. but i prefer to see how webaudio works from scratch to have 0 surprises, to understand how everything works, what is possible etc.

Also it's really more practical to have a hand on the dependance you use, i mean with gs-webaudio-library i recode only what i need when i need it, and when what i needed changed, i can update directly the library with what i want etc.

I didn't understood exactly what is Tiki yet
