### ISSUE TITLE
Feature Request: Bring back Wav Files

### ISSUE THREAD

**Issue by mistaox** [gridsound/daw#49]
In the previous version of the DAW, there was the ability to sequence WAV files.
Will you be adding that option to this version?
here is a image from a fork: https://raw.githubusercontent.com/Hostworks/SoundScaping/master/soundscape.png

**Comment by mr21** [comment]
Yes this would be added again for sure, the reason why i chose to remove this huge feature was to have better foundations, and we have better foundations now :)

But im sorry it will take some time before being able to drag samples..

**Comment by mistaox** [comment]
Well, please do.
Im looking to add such a feature t my music licencing website.

**Comment by mr21** [comment]
If you are not a user, but if you just want to c/c the code, then show more respect please.

**Comment by mistaox** [comment]
I didnt mean to be disrespectful or simply run off with your code. In fact i would like to hire you to develop a custom version with Wav edit capabilities. Thats why I spoke about the earlier version

**Comment by mistaox** [comment]
Just set you a message on via Facebook.

**Comment by mr21** [comment]
Guess who's back?

![](https://pbs.twimg.com/media/EBKdIUQX4AI_Yz0?format=jpg)
