### ISSUE TITLE
Unauthorized Distribution is Against the Law

### ISSUE THREAD

**Issue by askoz** [gridsound/daw#53]
When you place a box like "Drag and Drop raw file" that can allow any user to put whatever he wants inside a streaming flow in Internet, there are some aspects to consider related to security and copyright law, to avoid a "risk" content.
                                                    
- Copyright law protects the value of a creative work made by an artist. 

- Federal law provides severe civil and criminal penalties for the unauthorized reproduction, distribution,  rental or digital transmission of copyrighted sound recordings. (Title 17, United States Code, Sections 501 and 506).

- Regardless of the format at issue, the same basic principle applies: music sound recordings may not be copied or distributed without the permission of the owner.

- You can record your voice to stream any kind of outlaw message without chance to stop it.

**Comment by askoz** [comment]
The critical point is when you decide that your application should stream or share.

For example if GridSound adds a feature that let your composition be transmitted by a streaming Server to have a live radio on the net.

I don't know very well FLStudio, Reason, Cubase, Ableton, Protools but meanwhile you create your sound, simply mixing two copyrighted song, and all music remains in your pc there is no problem.

**Comment by mr21** [comment]
@askoz thx for your two issues :)
Yes GridSound will be used to share at least for sure, your concerne are right.

I'll be oblige to think about all that when i will take the time to let the samples being saved in our servers anyway. I'll add some CGU to legally prevent users sharing copyrighted musics, and as you said on your precedent post, this will need a report button obviously (for users who will try to abuse of the system). Do we need something else? idk

**Comment by askoz** [comment]
If you want to share music on other platform (Facebook, YouTube ...) you could make like
 Freedsound  https://freedsound.cc  that provides a form for DMCA Request:
 
	A DMCA notice informs a company, web host, search engine, or internet service provider 
	that they are hosting or linking to material that infringes on a copyright. 
	DMCA stands for Digital Millennium Copyright Act. 
	A DMCA notice is also known as a DMCA takedown notice or a DMCA request.
 
 Although your case is a little bit different because your source of content is undefined ......

![DMCARequest](https://user-images.githubusercontent.com/22682952/65598910-cdabee80-df9c-11e9-8a9e-1d03a415fccb.png)

**Comment by mitni455** [comment]
@askoz are you a developer? It looks like you've made an account and only one comment - this one. 

I move to close this issue as not a development issue and there are other more appropriate channels if this dude wants to spend his/her time threatening open source developers with legal action from hypotheticals.

**Comment by mitni455** [comment]
> The critical point is *when* you decide that your application should stream or share.

@askoz 
"when you decide" 
... *when* 

It's not even a feature yet so just f**k off

**Comment by mr21** [comment]
Hi @mitni455 to be honest it's me who ask @askoz to open a new separated issue for this problem
see this one: https://github.com/gridsound/daw/issues/52
At the begining he help me to find a bug, so thx to him

But yeah this issue looks like somebody who wants to stop a party, but not at all, then we need to keep calm and enjoy. Anyway, thx for your support, and checkout the new version :)
