### ISSUE TITLE
Is it possible to use .wav sample in piano roll?

### ISSUE THREAD

**Issue by Catsvilles** [gridsound/daw#55]
I tried playing around GridSound and use audio samples as instrument but looks like currently we can only add the sample to the timeline? Am I missing something? Thank you! :)

**Comment by mr21** [comment]
Hi, the audio samples can also be used into the **drums** windows.
But yes, we should be able to use them into the synths too. Also related to this, soon enough it'll be possible to change the pitch of each drum, like we can change the gain of each key.
