### ISSUE TITLE
Account registration not working

### ISSUE THREAD

**Issue by ambival3nt** [gridsound/daw#60]
The page works fine, I got the email, but when I clicked the verification link, I got: 

{"ok":false,"code":404,"msg":"No match for '(my email address)@outlook.com' with code 'd26356' (the code could be expired)"}

**Comment by mr21** [comment]
Hi :)

I see that you've checked your email now, i've reproduce the signup process and i realise that nothing says you that the link worked fine, then if after you reclick the same link in the same email, then you will have this exact error.

Is it what you have done?

**Comment by ambival3nt** [comment]
It was the first time I clicked?

But I dunno. Either way I really like your DAW
