### ISSUE TITLE
Drums Panel is broken.

### ISSUE THREAD

**Issue by zarp-dev** [gridsound/daw#63]
![image](https://user-images.githubusercontent.com/65812041/101147063-eeee7d00-362c-11eb-95f5-59dbaf0e42c4.png)
If you try to rearrange drums (move up or down) they will vanish.

**Comment by mr21** [comment]
hi @zarp-dev, sadly you right, i'm on it, sorry for the inconvenience

**Comment by mr21** [comment]
Also, why on your screen it's looks like you don't have all the vertical lines? are you on chrome/edge windows?

**Comment by mr21** [comment]
It's fixed :) thx for your report

**Comment by zarp-dev** [comment]
Thank you for making such great software! :)

**Comment by zarp-dev** [comment]
> Also, why on your screen it's looks like you don't have all the vertical lines (the steps' lines to be exact)? are you on chrome/edge windows?

I'm on Ubuntu 20.04 and I'm using Firefox.
