### ISSUE TITLE
Drumcuts do not register when playing a cloud-stored song from a user's page

### ISSUE THREAD

**Issue by gabeklavans** [gridsound/daw#69]
Steps to reproduce:
* Create a new song
* Create a drum beat with some drumcuts
* Login and save the song to the account's cloud storage
* Go to your user page and play the stored song from there

Drumcuts now register as a regular sample trigger rather than a stop trigger in this playback

**Comment by mr21** [comment]
Hi gabeklavans,

Indeed you right, the code on the website has an old version of the code.. everything will be fixed this weekend..
Thx for your issue, sorry for the bug

**Comment by mr21** [comment]
The website has been updated only now.. thx for your patience
