### ISSUE TITLE
Release tags?

### ISSUE THREAD

**Issue by mxmilkiib** [gridsound/daw#70]
Hi, I'd like to list this project on https://libreav.org/updates but there are no git tags to appear in the /releases.atom feed. Might it be possible for those to be used?

**Comment by mr21** [comment]
Indeed i should use something like this, does the GitHub's tags would be enough?
Anyway, we will see this next year ;)

**Comment by mxmilkiib** [comment]
Yup, that'd be enough. A basic bump like https://github.com/VCVRack/Rack/releases/tag/v2.0.6 would be enough, though adding information to the message would help inform folk here.

**Comment by mr21** [comment]
Hi, this has been done btw
For example, here the current one https://github.com/gridsound/daw/releases/tag/0.37.2

thanks again
