### ISSUE TITLE
Keyboard: Octave change

### ISSUE THREAD

**Issue by pjburnhill** [gridsound/daw#82]
First of all, excellent project, well done! Will keep a sharp eye to see how it progresses!

Issue: I noticed that the computer keyboard functions as piano keys, great! The only issue is that I can't seem to change octave, has this not implemented yet?

Would be really helpful, especially when testing bass melodies.

Keep it up!

**Comment by mr21** [comment]
You right, i need this feature too

**Comment by mr21** [comment]
Done!

![image](https://user-images.githubusercontent.com/850754/206874943-15607309-1dc5-49c1-9e02-83e034c5d0ed.png)

**Comment by pjburnhill** [comment]
Brilliant! Nicely done!
