### ISSUE TITLE
Corrupted project?

### ISSUE THREAD

**Issue by pjburnhill** [gridsound/daw#85]
Hey,

I returned to my project after a day or two, and now the synths are not firing and only the first bar of the drum pattern plays whenever the pattern starts. Has the file been corrupted somehow?

I have one local file in the project, which of course won't play unless you have loaded it in, but neither is anything else, except the first bar of drums.

Here is the json project:
[Drum & Bass Test (1).zip](https://github.com/gridsound/daw/files/10245819/Drum.Bass.Test.1.zip)

**Comment by pjburnhill** [comment]
FYI - this is not the project you recovered. This is an older version I had saved locally.

**Comment by pjburnhill** [comment]
Was the json schema changed by any chance?

**Comment by pjburnhill** [comment]
Just tested a few of the demo projects and none of them seem to work either..

**Comment by mr21** [comment]
I have just forgetten the detunefine for the old compositions' oscillator in a formatting function
I was testing with my own test, but to be sure i have test with your drumnbass test file,
HAHA then what a test! i was so surprised when i heard a new sound 😌

im so impressed so much creativity with the multiple delays and i didnt have access to the file needed for the slices

Also for your convenience when the main app have a regression you can use an older version like https://gridsound.com/daw/old/0.38.0
https://github.com/gridsound/daw/wiki/versions

**Comment by mr21** [comment]
its now fixed on the current version 0.39.1
