### ISSUE TITLE
New Oscillator Bug 

### ISSUE THREAD

**Issue by End3r6** [gridsound/daw#86]
Hey,

First thing first, thanks for this. It is cool and works well (aside from a few minor bugs ). 
One of these bugs I found while making a synth, the new oscillator button seems broken. When I click it, nothing happens.

Not sure if this is a bug or if I don't know what I am doing, but it might be worth looking into.

edit: while testing this more, it only seems to be broken sometimes. 🤔

**Comment by mr21** [comment]
Indeed, you can't add a new oscillator while the synthesizer is used.. weird
thx for the issue

**Comment by mr21** [comment]
Hi, this has been fixed in the 0.39.2 version
Thank you again
