### ISSUE TITLE
How to upload drum samples to drum roll

### ISSUE THREAD

**Issue by IdRatherNotBe** [gridsound/daw#89]
- I'm trying to make a trap song, but I don't know how to connect drum samples to the drum loop.
[Screen recording 2023-04-17 7.16.23 AM.webm](https://user-images.githubusercontent.com/131002752/232512804-b05b1cce-c32a-4e80-9c46-13099831615d.webm)

**Comment by mr21** [comment]
here you have a screenshot which explain you how to do it https://github.com/gridsound/daw/issues/81
It could be simpler indeed

also you make me realise that there is an issue, you cant do it if you have deleted all the previous buffers, i will fix that ASAP

**Comment by IdRatherNotBe** [comment]
Thank you!!

**Comment by mr21** [comment]
you're welcome :)

So even if you delete all the buffers, you can follow the screenshot ive linked to you.

**Comment by IdRatherNotBe** [comment]
Where is the screenshot? (I'm new here)
